src/BestFriends/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('app.urls')),
    #path('admin/', admin.site.urls)
    ]

src/app/urls.py
from django.urls import path
from django.conf.urls import url,include

from . import views
app_name = 'app'
urlpatterns = [path('',views.home,name="home"),
    path('api',include('app.api.urls')),
    path('home',views.home,name="home"),
    path('contact',views.contact,name="contact"),
    path('about',views.about,name="about"),
    path('birthday',views.birthday,name="birthday"),

    path('login',views.login,name="login"),

    path('<str:user_id>/ai',views.ai,name="ai"),

    # if no url pattern matches the url from client, throw a 404 page
    url(r'',views.error404,name='404error')]

src/app/templates/app/404error.html
{% extends "app/layout.html" %} {% block content %}

<h1>404 Page Not Found</h1>
<p>Hey, you might mistype the URL.</p>
<p>
  If this page did exist, we may have deleted it. Sorry for any inconvenience.
</p>
<a href="{% url 'app:home' %}">Click here to go back to <strong>Home</strong> page</a>
{% endblock %}

src/app/templates/app/about.html
{% extends "app/layout.html" %}
{% block header %} {% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'app/content/about_page.css' %}" />


{% endblock %}
{% block content %}
<div class="title">
    <h2>
        <strong>{{ title }}.</strong>
    </h2>


    <h3>
        Two software students Kexin Huang & Dewei Liu have been developing this web app since 14 Aug 2018! Naming this
        project as Best Friends App is for memorising the long-term friendship.
        <br />
        <a href="https://github.com/deweiliu/best-friends">Click here to see this project on <img
                src="{% static 'app/images/github_logo.png' %}" alt="GitHub Logo"> GitHub</a>
        <br />
        (Last updated on {{update_date}})
    </h3>
    <p>This project is using multiple servers and their intergration based on Microsoft Azure Cloud Service, including
        <a href="https://azure.microsoft.com/en-gb/services/app-service/web/"> Web App</a>,
        <a href="https://en.wikipedia.org/wiki/Microsoft_SQL_Server"> SQL Database</a>,
        <a href="https://azure.microsoft.com/en-us/services/bot-service/"> Azure Bot service (Direct Line API) </a> and
        <a href="https://www.qnamaker.ai/">QnAMaker</a>. All of these servers are hosted on Azure Web App service, and
        this app uses Django Framework written in Python 3.
        Clients can only contact the app so other servers are hidden from clients. This makes sure that other servers
        are in safe and won't get exposed in public.</p>
    <br />
    <p> <strong>Because of our limited budget, the performance of the servers is quite low, so please be paitent to the
            delays while you are using the app.</strong></p>

    <h4>Please see the images below to check out how it works.</h4>
</div>
<br />
<br />
<div class="illustration">
    <h3>Login page</h3>
    <p>When you log in with your first name and surname, the app checks if you are a registered user by checking your
        name.
        <ul>If it is, it redirects you to an URL with your user ID number.</ul>
        <ul>If it is not, it assigns a new user ID to you and redirects you to an URL with your user ID number.</ul>
    </p>
    <img src="{% static 'app/images/documentation/Slide1.JPG' %}" alt="Login">
</div>

<br />
<br />
<div class="illustration">
    <h3>Starting the conversation</h3>
    <p>The app then receives the URL with your user ID. It queries the SQL database for your details and chatting
        history.
        Then it shows you the AI dialog and your previous messages (if any).
        At the same time, the app send HTTP request to The Azure Bot to start a conversation with your bot credentials.
        <br /><strong>Note, the bot credentials are used for accessing the bot and identifing which messages are from a
            same conversation/user. These are required by "Direct Line API", and not controlled by you. (not your login
            details)</strong></p>
    <img src="{% static 'app/images/documentation/Slide2.JPG' %}" alt="start conversation">
</div>

<br />
<br />

<div class="illustration">
    <ul>
        <h3>Sending a message</h3>
        <li><strong>Client side (your browser)</strong>: sends a message to the app, and keeps sending HTTP request to
            ask if there are new messages updated.</li>
        <li><strong>App side</strong>: lodges the message to database, restructures the message, and sends it to the
            Bot.</li>
        <li><strong>Azure Bot</strong>: Asks the QnAMaker to find a question from knowledge base that matches the
            question asked by the user, and temporaryly stores the answer.</li>
    </ul>
    <img src="{% static 'app/images/documentation/Slide3.JPG' %}" alt="send a message">
</div>


<br />
<br />
<div class="illustration">
    <ul>
        <h3>Receiving a message</h3>
        <li><strong>Client side (your browser)</strong>: Keeps sending request asking the app if there are any new
            messages.</li>
        <li><strong>App side</strong>: <br />1. For every request received from client, checks with the database. If
            there are any, send the messages back to client. <br />
            2. Keeps asking the Bot if the answer is ready. Once the answer is ready, lodges the answer to the database.
        </li>
        <li><strong>Azure Bot</strong>: When receiving request from the app, sends the answer back.</li>
    </ul>
    <img src="{% static 'app/images/documentation/Slide4.JPG' %}" alt="receive a message">
</div>



{% endblock %}

src/app/templates/app/ai.html
{% extends "app/layout.html" %} {% block header %} {% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'app/content/ai_page.css' %}" />

{% endblock %} {% block content %}

<div class="title">
  <h1>AI Robert</h1>
  <h2>Welcome {{ firstname }}</h2>
</div>

<div class="conversation">
  <div class="status-bar">
    <div class="time" id="show_now_time">time</div>
    <div class="entypo-clock"></div>
  </div>
  <div class="chatting_display" id="chatting_dialog">
    <div class="heading" id="head"></div>
    <div class="user"></div>
    <div class="robot"></div>
  </div>
  <div class="talk_input">
    <input type="text" class="sending_words" id="input_words" name="Twords" placeholder="Just say Hello" />
    <input type="button" value="send" class="talk_submit" id="talksubmit" />
  </div>
</div>

{% endblock %} {% block scripts %}
<script src="{% static 'app/scripts/ai_dialog.js' %}"></script>
<script src="{% static 'app/scripts/show_now_time.js' %}"></script>
<script>
  var firstname = "{{firstname}}";
  var surname = "{{surname}}";
  var user_id = "{{user_id}}";
</script>

{% endblock %}

src/app/templates/app/birthday.html
{% extends "app/layout.html" %} {% block header %} {% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'app/content/birthday_page.css' %}" />

{% endblock %} {% block content %}

<br />
<div class="title">
  <h2>
    <strong>{{ title }}.</strong>
  </h2>

  <p>{{ content }}</p>
</div>

<div id="deiwei_birthday" class="Birthday_show fadeInDown animated">
  <div class="container">
    <div class="download-head">
      <h3>To dewei:happy birthday!</h3>
      <br />
      <h4><span>2018-11-21</span></h4>
    </div>
  </div>
</div>

<br />
<div class="wishes fadeInLeft animated">
  <p>Bless you back to China safely!!</p>
</div>

<br />
<div class="kexin_birthday"><span id="dateField">hi</span></div>

<br />

<br />

<div class="comment">
  <br />
  {% for comment in comments %}
  <span> At {{ comment.datetime }}, user
    <strong>{{ comment.username }}</strong> said:</span>
  <div class="comment_show">
    <h3>
      <span>{{ comment.comment }}</span>
    </h3>
  </div>

  <br />

  {% endfor %}
</div>

<br />
<div class="login_center">
  <h3>Hi, before you leave, just leave a comment below pleeeeEEEeeease</h3>
  <p>
    In the moment, we can only support alphabet letters. Entering other
    characters will cause display issues
  </p>
  <form action="{%url 'app:birthday' %}" method="post">
    {% csrf_token %} <br />
    <label for="user_name">Enter name below </label>
    <input id="user_name" type="text" class="form-control" name="username" margin="auto"
      placeholder="i.e. John Smith" />
    <br />
    <br />
    <label for="comment">Enter your comment below </label> <br />
    <input id="comment" type="text" class="form-control" name="comment" margin="auto" placeholder="i.e. Hi! Birthday" />
    <br />
    <br />
    <input type="submit" class="btn_input" value="submit" id="sub_username" />
  </form>
</div>

{% endblock %} {% block scripts %}
<script src="{% static 'app/scripts/BirthdayTimeLeft.js' %}"></script>

{% endblock %}

src/app/templates/app/contact.html
{% extends "app/layout.html" %}
{% block header %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'app/content/contact_page.css' %}" />
{% endblock %} {% block content %}

<h1>&nbsp;</h1>
<section class="contact">
  <br />
  <article>
    <h2>
      <strong>{{ title }}.</strong>
    </h2>
    <h3>{{ message }}</h3>

    <address></address>

    <address>
      <strong>Website:</strong>
      <a href="https://deweiliu.com/">deweiliu.com</a>
      <br/>
    </address>
  </article>
</section>

{% endblock %}

src/app/templates/app/index.html
{% extends "app/layout.html" %} {% block header %} {% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'app/content/index_page.css' %}" />
{% endblock %} {% block content %}
<div class="jumbotron">
  <h1><strong>Best Friends App</strong></h1>
  <p class="lead fadeInUp animated"><strong>
      Best Friends App is an AI Bot hosted on Microsoft Azure.<br /> Please click the button below to start chatting
      with the Bot!
    </strong></p>
  <p>
    <a href="{%url 'app:login' %}" class="btn btn-primary btn-large">Start chatting &raquo;</a>
  </p>
</div>
<div class="row">

  <div class="col-md-6 fadeInLeft animated">

    <div class="border">
      <h2><strong>Severe Delays?</strong></h2>
      <p>Because of our limited budget on this project, the performance of the servers is quite low, so please be
        paitent to the delays while you are using the app.</p>
      <p>
        <a class="btn btn-default" href="{%url 'app:login' %}">Check out the app carefully :) &raquo;</a>
      </p>
    </div>

  </div>

  <div class="col-md-6 fadeInRight animated">

    <div class="border">
      <h2><strong>How it works</strong></h2>
      <p>Check out how the whole project works.</p>
      <p>
        <a class="btn btn-default" href="{%url 'app:about' %}">See how it works &raquo;</a>
      </p>
    </div>

    <div class="border">

      <h2><strong>Need help?</strong></h2>
      <p>
        Please contact us via email!
      </p>
      <p>
        <a class="btn btn-default" href="{%url 'app:contact' %}">Contact &raquo;</a>
      </p>
    </div>
  </div>
</div>

{% endblock %} { {% block scripts %}

{% endblock %}

src/app/templates/app/layout.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no" />
  {% load staticfiles %}
  <link rel="icon" type="image/png" href="{% static 'app/images/favicon.ico' %}" />
  <meta name="theme-color" content="#40B1FA">

  <title>{{ title }} - Best Friends App</title>

  <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'app/content/animate.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'app/content/style.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'app/content/magnific-popup.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'app/content/background.css' %}" />
  <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
  <script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
  <script type="text/javascript" src="{% static 'app/scripts/easing.js' %}"></script>

  {% block header %}{% endblock %}
</head>

<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span> <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand"><strong>Best Friends App</strong></a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'app:home' %}">Home </a></li>
          <li><a href="{% url 'app:login' %}">AI App</a></li>
          <li><a href="{% url 'app:birthday' %}">Birthday</a></li>
          <li><a href="{% url 'app:about' %}">About</a></li>
          <li><a href="{% url 'app:contact' %}">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="night">
    <div class="shooting_star"></div>
    <div class="shooting_star"></div>
    <div class="shooting_star"></div>
    <div class="shooting_star"></div>
    <div class="shooting_star"></div>
    <div class="shooting_star"></div>
    <div class="shooting_star"></div>
    <div class="shooting_star"></div>
    <div class="shooting_star"></div>
    <div class="shooting_star"></div>
    <div class="shooting_star"></div>
    <div class="shooting_star"></div>
    <div class="shooting_star"></div>
    <div class="shooting_star"></div>
    <div class="shooting_star"></div>
    <div class="shooting_star"></div>
    <div class="shooting_star"></div>
    <div class="shooting_star"></div>
    <div class="shooting_star"></div>
    <div class="shooting_star"></div>
  </div>

  <div class="container body-content">
    {% block content %}{% endblock %}
    <hr />
    <footer>
      <p>&copy; {{ year }} - Best Friends App</p>
    </footer>
  </div>
  <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
  <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
  <script src="{% static 'app/scripts/respond.js' %}"></script>
  {% block scripts %}{% endblock %}
</body>

</html>

src/app/templates/app/login.html
{% extends "app/layout.html" %} {% block header %} {% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'app/content/login_page.css' %}" />
{% endblock %} {% block content %}


<div id="contact" class="Contact">
  <div class="contact-map">

    <div class="contact-form">
      <div class="bubble" id="show_bubble"></div>
      <div class="contact-head">
        <h4>Log in/Sign up</h4>
      </div>
      <form action="{%url 'app:login' %}" method="post">
        {% csrf_token %}
        <input type="text" class="text" id="first_name" name="first_name" margin="auto" placeholder="first name" />
        <input type="text" class="text" id="surname" name="surname" margin="auto" placeholder="surname" />

        <br />
        <br />
        <div class="sub-button">
          <input type="submit" name="bottom" value="Enter" id="sub_username" />
        </div>
        <p>Please be patient when we are processing your details. It may take a while.</p>
      </form>
    </div>
  </div>
</div>

{% endblock %} {% block scripts %}
<script src="{% static 'app\scripts\login_page.js' %}"></script>
{% endblock %}